### ISSUE TITLE
Please update node package

### ISSUE THREAD

**Issue by mikeymckay** [osher/ddocs#1]
It still has the path error in it.

**Comment by osher** [comment]
Could you please elaborate?

I have this package in production for years now, I would like to learn what error do you experience...

**Comment by mikeymckay** [comment]
When I download the package via node from here:
https://www.npmjs.com/package/ddocs

It still has the path error that you fixed in this commit:
https://github.com/osher/ddocs/commit/361434abfcadf21d71336d4a215276f1f18fb6a9

**Comment by osher** [comment]
Oi. you're right...
looks like I published to the propriatry repo...

here, I published + ddocs@1.0.0

Thanks!
